export const ROOT_URL = 'https://jjjwelch420.github.io/Launcher-S/';
export const games = [
  { id: 'Racing', label: 'Racing' }, 
  { id: 'StickWar', label: 'Stick War' },
  { id: 'ARC', label: 'ARC' },
  { id: 'SprinterFlash', label: 'Sprinter Flash' },
  { id: 'Minecraft', label: 'Minecraft' },
  { id: 'GunSpin', label: 'Gun Spin' },
  { id: 'OvO', label: 'OvO' },
  { id: 'Cookie', label: 'Cookie Clicker' },
  { id: 'SM64', label: 'Super Ah 64' }, 
  { id: 'Drift-RU', label: 'Drift Hunters' },
  { id: 'Funny2', label: 'Funny Shooter' },
  { id: 'SnowRiders', label: 'Snow Riders' },
  { id: 'Riddle-1', label: 'Riddle School 1' },
  { id: 'Riddle-2', label: 'Riddle School 2' },
  { id: 'Riddle-3', label: 'Riddle School 3' },
  { id: 'Riddle-4', label: 'Riddle School 4' },
  { id: 'Riddle-5', label: 'Riddle School 5' },
  { id: 'Riddle-T1', label: 'Riddle School Transfer 1' },
  { id: 'Riddle-T2', label: 'Riddle School Transfer 2' },
  { id: 'LearnToFly', label: 'Learn to Fly' },
  { id: 'Learn2Fly', label: 'Learn to Fly 2' },
  { id: 'LearnToFly3', label: 'Learn to Fly 3' },
  { id: 'PapasSushiria', label: 'Papa\'s Sushiria' },
  { id: 'PapasBurgeria', label: 'Papa\'s Burgeria' },
  { id: 'PapasPizzeria', label: 'Papa\'s Pizzeria' },
  { id: 'PapasHotdogeria', label: 'Papa\'s Hotdogeria' },
  { id: 'Red-vs-Blue', label: 'Red vs Blue' },
  { id: 'JackSmith', label: 'JackSmith' },
  { id: 'BasketballLegends', label: 'Basketball Legends' } 
    ];
